debug: false

# Application
spring:
  application:
    name: server
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: inserisci-db

# Kafka
kafka:
  hostname: localhost:9092
  groupid: serverGroup
  channels:
    in: iotData_meteo_2020_gennaio_marzo,iotData_suolo_1_2020,iotData_suolo_2_2020,iotData_suolo_3_2020,iotData_suolo_4_2020,iotData_suolo_5_2020,iotData_suolo_6_2020,iotData_suolo_7_2020,iotData_suolo_8_2020,iotData_suolo_9_2020
