debug: false

# Application
spring:
  application:
    name: server

# Kafka
kafka:
  hostname:
    localhost:9092
  groupid:
    serverGroup
  channels:
    in: iotData_meteo_2020,iotData_suolo_1_2020
